security:
    providers:
        from_database:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            pattern: ^/
            provider: from_database
            form_login:
                login_path: app_login
                check_path: app_login
                csrf_token_generator: security.csrf.token_manager
            logout: true
            guard:
                authenticators:
                    - App\Security\UserAuthenticator
            remember_me:
                secret: '%kernel.secret%'

    access_control:
        - { path: ^/admin/user, roles: ROLE_SUPER_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/conversation, roles: ROLE_USER }
    role_hierarchy:
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_ADMIN: ROLE_MODO
        ROLE_MODO: ROLE_USER
    encoders:
        App\Entity\User:
            algorithm: auto
            cost: 12

