#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# login:
#     path: /login
#     controller: App\Controller\MemberController::login
logout:
    path: /logout
    methods: GET